galaxy_info:
  author: Mubarak
  description: >
    An Ansible role to install and configure OpenJDK using manually downloaded binaries. 
    Useful for environments (e.g. RHEL 7) where default Java roles fail or repositories are outdated.
  company: DevOps Community
  license: MIT
  min_ansible_version: 2.9
  galaxy_tags:
    - java
    - jdk
    - rhel
    - ansible-role
    - openjdk
    - automation
dependencies: []
