---
- name: Check if Java 21 is installed
  shell: java -version 2>&1 | grep -q "version \"21"
  register: java_21_check
  ignore_errors: yes
  changed_when: false

- name: Set Java installation needed fact
  set_fact:
    java_install_needed: "{{ java_21_check.rc != 0 }}"

- name: Download the JDK binaries
  get_url:
    url: "{{ jdk_download_url }}"
    dest: "{{ jdk_download_location }}"
  when: java_install_needed

- name: Unzip the downloaded file
  unarchive:
    src: "{{ jdk_download_location }}"
    dest: /opt
    remote_src: yes
  when: java_install_needed

- name: Find JDK 21 directory
  find:
    paths: /opt
    patterns: "jdk-21*"
    file_type: directory
  register: jdk_dir
  when: java_install_needed
  tags: ["java"]

- name: Set Java home fact
  set_fact:
    java_home: "{{ jdk_dir.files[0].path }}"
  when: java_install_needed

- name: Set the JAVA_HOME in /etc/profile file
  lineinfile:
    path: /etc/profile
    state: present
    backup: yes
    line: "{{ item }}"
  with_items:
    - 'export JAVA_HOME="{{ java_home }}"'
    - "export PATH=$PATH:$JAVA_HOME/bin"
  when: java_install_needed
  notify: Reload profile # Trigger profile reload
  tags: ["java", "config"]

- name: Remove existing Java symbolic link
  file:
    path: /bin/java
    state: absent
  become: yes
  when: java_install_needed
  tags: ["java", "symlink"]

- name: Create symbolic link to Java 21
  file:
    src: "{{ java_home }}/bin/java"
    dest: /bin/java
    state: link
  become: yes
  when: java_install_needed

- name: Verify Java 21 installation
  shell: java -version 2>&1 | grep -q "version \"21"
  register: java_verify
  failed_when: java_verify.rc != 0
  changed_when: false
  when: java_install_needed
  tags: ["verify"]
