---
- name: Java Installation Block
  block:
    - name: Ensure Java install directory exists
      file:
        path: "{{ install_path }}"
        state: directory
        owner: root
        group: root
        mode: "0755"

    - name: Check if Java {{ java_version }} is already installed
      shell: java -version 2>&1 | grep -q "version \"{{ java_version }}"
      register: java_check
      ignore_errors: yes
      changed_when: false

    - name: Set Java installation needed fact
      set_fact:
        java_install_needed: "{{ java_check.rc != 0 }}"

    - name: Download JDK binary
      get_url:
        url: "{{ jdk_download_url }}"
        dest: "{{ install_path }}/jdk-{{ java_version }}_{{ java_platform }}.tar.gz"
      when: java_install_needed

    - name: Extract the JDK archive
      unarchive:
        src: "{{ install_path }}/jdk-{{ java_version }}_{{ java_platform }}.tar.gz"
        dest: "{{ install_path }}"
        remote_src: yes
      when: java_install_needed

    - name: Discover JDK install path
      find:
        paths: "{{ install_path }}"
        patterns: "jdk-{{ java_version }}*"
        file_type: directory
      register: jdk_dir
      when: java_install_needed

    - name: Set JAVA_HOME variable
      set_fact:
        java_home: "{{ jdk_dir.files[0].path }}"
      when: java_install_needed

    - name: Export JAVA_HOME in /etc/profile
      lineinfile:
        path: /etc/profile
        line: "{{ item }}"
        state: present
        backup: yes
      loop:
        - "export JAVA_HOME={{ java_home }}"
        - "export PATH=$PATH:$JAVA_HOME/bin"
      when: set_java_home | bool
      notify: Reload profile

    - name: Remove old Java binary symlink (if any)
      file:
        path: /usr/bin/java
        state: absent
      when: java_install_needed

    - name: Create symlink for java
      file:
        src: "{{ java_home }}/bin/java"
        dest: /usr/bin/java
        state: link
      when: java_install_needed

    - name: Confirm Java {{ java_version }} installed
      shell: java -version 2>&1 | grep -q "version \"{{ java_version }}"
      register: java_verify
      failed_when: java_verify.rc != 0
      changed_when: false
      when: java_install_needed

  become: true
  tags: [java]
