- name: Install Java using custom Ansible role
  hosts: all
  become: true
  vars:
    java_version: "21"
    install_path: "/opt/java"
    set_java_home: true
  roles:
    - role: java_install
      tags: ["java"]
