---
- name: Install Java using custom Ansible role
  hosts: all
  become: true
  vars:
    java_distribution: "adoptium"
    java_version: "24"
    install_path:
      "/opt/java"
      # Make sure this path is correct and the file exists
    custom_jdk_path: "/home/mubarak/Downloads/jdk-17.0.15_linux-x64_bin.tar.gz"

  roles:
    - role: java_install
      tags: ["java"]
