- name: Install Java using custom Ansible role
  hosts: all
  become: true
  vars:
    java_distribution: "oracle"
    java_version: "17"
    install_path: "/opt/java"
  roles:
    - role: java_install
      tags: ["java"]
